import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Preloader from "../components/preloader";
import axios from "axios";

export default function Home() {
  const [token, setToken] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState(false);
  const [success, setSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState(null);

  const updateToken = (e) => {
    setToken(e.target.value);
  };

  const verifyToken = async (e) => {
    e.preventDefault();
    setError(false);
    setLoading(true);

    try {
      const res = await axios.get(
        `http://127.0.0.1:8000/api/authenticate/${token.replace(
          /[^\w\s]/gi,
          ""
        )}`,
        {
          headers: {
            Accept: "application/json",
          },
          validateStatus: false,
        }
      );
      console.log(res.data);
      setMessage(res.data.message);
      if (res.data.status === "success") {
        setData(res.data.site);

        setTimeout(() => {
          setSuccess(true);
        }, 1500);

        setTimeout(() => {
          window.location = `${res.data.site.web_address}?rqid=${res.data.auth_id}`;
        }, 4000);
      } else {
        setTimeout(() => {
          setError(true);
          setLoading(false);
        }, 1500);
      }
    } catch (err) {
      setMessage(err.message);
      setError(true);
      setLoading(false);
      console.log(err);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Cyaen Client Site</title>
        <link rel="stylesheet" href="/mdb.min.css" />
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossOrigin="anonymous"
        />

        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
        <script
          type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"
        />
      </Head>
      <header className="header text-white text-center">
        <img src="/cyaen-logo.svg" className="headerLogo " />
        <h1 className="heading-1 fw-re  mt-4">welcome to our client site</h1>
        <h4 className="paragraph-2 fw-li w-75 mx-auto m-0">
          please enter your site auth key to proceed
        </h4>
        <div className="mt-5 col-10 col-md-7 mx-auto">
          <form onSubmit={(e) => verifyToken(e)}>
            <input
              value={token}
              onChange={updateToken}
              type="text"
              required
              minLength="32"
              data-mdb-showcounter="true"
              id="form1"
              className={error ? "form-control is-invalid" : "form-control"}
              placeholder="e.g 9hlIKXBPJdy1BgRktcBGmpjsf9XPLK5a"
            />
            {error && (
              <div className="small text-danger mt-2 fw-bo pulse">
                <i className="fas fa-exclamation-triangle me-2"></i>
                {message}
              </div>
            )}

            {loading ? (
              <button type="submit" className="btn btn-secondary mt-3">
                <span className="pulse">VERIFYING.....</span>
              </button>
            ) : (
              <>
                {error ? (
                  <button type="submit" className="btn btn-danger mt-3">
                    RETRY
                  </button>
                ) : (
                  <button type="submit" className="btn btn-primary mt-3">
                    VERIFY TOKEN
                  </button>
                )}
              </>
            )}
          </form>
        </div>
      </header>
      <Preloader loading={loading} success={success} data={data} />
      <div className={styles.clouds}></div>
    </div>
  );
}
